name: CI

on:
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1

      - name: Install dependencies
        uses: bahmutov/npm-install@v1

      - name: Run tests
        run: npx yarn test

      - name: Run lint
        run: npx yarn lint

      - name: Run build
        run: npx yarn build
